ARG ERPNEXT_IMAGE=frappe/erpnext:develop
FROM ${ERPNEXT_IMAGE}

USER root
COPY docker/coolify-entrypoint.sh /usr/local/bin/coolify-entrypoint.sh
RUN chmod 755 /usr/local/bin/coolify-entrypoint.sh

USER frappe
WORKDIR /home/frappe/frappe-bench

COPY --chown=frappe:frappe . apps/hrms

RUN echo "Base apps before HRMS install:" \
	&& ls -1 apps \
	&& test -d apps/frappe \
	&& test -d apps/erpnext \
	&& test -f apps/hrms/hrms/hooks.py

RUN ./env/bin/pip install --no-cache-dir --use-pep517 -e apps/hrms

RUN yarn --cwd apps/hrms install --check-files

RUN bench build --app hrms

RUN cp -r sites/assets ./assets \
	&& rm -rf sites/assets \
	&& rm -rf apps/hrms/.git

ENTRYPOINT ["/usr/local/bin/coolify-entrypoint.sh"]
